# Generated by Django 5.2.5 on 2025-08-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_question_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='diagram',
            field=models.ImageField(blank=True, null=True, upload_to='diagrams/'),
        ),
    ]
